### ISSUE TITLE
"pn_jobids_lst" not defined

### ISSUE THREAD

**Issue by niccarp** [waa/bacula#2] opened 2021-07-27 00:13 UTC
Hi,

I Just want report this error.

Bacula enterprise version 12.6.4, CentOS 7.9.2, mysql catalog,  python3.6.

~~~
[root@bacula-dir src]# python3.6 baculabackupreport.py -e email@email.com -f bacula@reporte.com --dbtype mysql --dbpass passwordSecret

Traceback (most recent call last):
  File "baculabackupreport.py", line 1072, in <module>
    print(pn_jobids_lst)
NameError: name 'pn_jobids_lst' is not defined`
~~~

I just add " pn_jobids_lst = [] " at line 1071 before the error and after the report finish without problems.

I hope this help or maybe has some impact.

Thanks for your work.

**Comment by waa** [comment] 2021-07-27 00:38
Thank you for the report.

Hmmm, what version is printed at the bottom of the report?  I just added some new features today, and made some commits, there should not be any 'print(pn_jobids_lst)' in the code unless I accidentally committed and pushed some testing version. :)

I have done a little more work this evening, so I may have already fixed this issue.

**Comment by niccarp** [comment] 2021-07-27 00:44
Hi ! 

Sorry, the print() was added by me in order to debug not in your code but the error with the var is the same.

At this line 1071 ->    if len(pn_jobids_lst) != 0:

Report version: 
Bacula Backup Report - v1.20 - baculabackupreport.py
By: Bill Arlofski waa@revpol.com (c) July 26, 2021

Great news, take a look and I will be follow the commits.

**Comment by waa** [comment] 2021-07-27 00:51
OK, I have reproduced the problem and I think I have fixed it. I will push a new version (1.21) shortly. 

The issue was that you apparently do not have any copy or migration jobs and because of this, that variable does not get created, but then I was referencing this non-existent variable later in the code.

Thank you again for the report.

**Closed** 2021-07-27 16:53 UTC
